spring.application.name=keystone

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/keystone_db
spring.datasource.username=postgres
spring.datasource.password=Vaibhav@0525
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8082}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.authorization=TRACE
 
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.access=TRACE

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.access=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true